version: '3.8'

services:
  api:
    build: .
    image: chat-app-api
    container_name: chat-app-api
    ports:
      - "8080:8080"
    networks:
      - chat-network

  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    image: chat-app-ui
    container_name: chat-app-ui
    ports:
      - "3000:3000"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
