// Code generated by swaggo/swag. DO NOT EDIT.

package doc

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/health":{"get":{"description":"Get the health status of the service","consumes":["application/json"],"produces":["application/json"],"tags":["health"],"summary":"Health check","responses":{"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"string"}}}}}},"/rooms":{"get":{"description":"List available chat rooms","consumes":["application/json"],"produces":["application/json"],"tags":["chat"],"summary":"Get chat rooms","responses":{"200":{"description":"OK","schema":{"type":"array","items":{"type":"string"}}}}},"post":{"description":"Create a new chat room","consumes":["application/json"],"produces":["application/json"],"tags":["chat"],"summary":"Create chat room","parameters":[{"description":"Room name","name":"room","in":"body","required":true,"schema":{"type":"object","additionalProperties":{"type":"string"}}}],"responses":{"201":{"description":"Room created","schema":{"type":"string"}}}}},"/rooms/{room}/bind":{"get":{"description":"Bind to a given chat room","consumes":["application/json"],"produces":["application/json"],"tags":["chat"],"summary":"Bind to chat room","parameters":[{"type":"string","description":"Room name","name":"room","in":"path","required":true},{"type":"string","description":"Nickname","name":"nickname","in":"query","required":true}],"responses":{"200":{"description":"Connected","schema":{"type":"string"}}}}},"/ws":{"get":{"description":"Establish and handle WebSocket connections","consumes":["application/json"],"produces":["application/json"],"tags":["websocket"],"summary":"Handle WebSocket connections","responses":{}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chat App API",
	Description:      "This is a sample server for a chat application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
