basePath: /
definitions:
  models.Message:
    properties:
      content:
        type: string
      nickname:
        type: string
      room:
        type: string
      timestamp:
        type: string
    required:
    - content
    - nickname
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a chat application.
  title: Chat App API
  version: "1.0"
paths:
  /api/v1/health:
    get:
      consumes:
      - application/json
      description: Get the health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
  /api/v1/rooms:
    get:
      consumes:
      - application/json
      description: List available chat rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get chat rooms
      tags:
      - chat
  /api/v1/rooms/{room}/bind:
    get:
      consumes:
      - application/json
      description: Bind to a given chat room
      parameters:
      - description: Room name
        in: path
        name: room
        required: true
        type: string
      - description: Nickname
        in: query
        name: nickname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Connected
          schema:
            type: string
      summary: Bind to chat room
      tags:
      - chat
  /api/v1/rooms/{room}/send:
    get:
      consumes:
      - application/json
      description: Send a message to a specific room identified by room ID
      parameters:
      - description: room ID
        in: path
        name: room
        required: true
        type: string
      - description: nickname
        in: path
        name: nickname
        required: true
        type: string
      - description: Payload with nickname and message
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send a message to a specific room
      tags:
      - websocket
swagger: "2.0"
